# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5970eedfe558d05337964d9deee10b30d44eed7fb75852d5a4b578a5a1eccc57c47719e1a7f64f1d5d38b153ccbcdd5915bc518437e5e63a8a101c55ee2a6bef

test:
  secret_key_base: b5c36ddcd94e15986976d2cd1ec17e8eebeaba79d933b1cd3565df542d869b73cf745496811df18a54a23f69d645ba4b72c0595d862643b3f8bfd6f7189968eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
